apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: playeconomyaxsg1-tls-cert
spec:
  secretName: playeconomyaxsg1-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - playeconomyaxsg1.eastus.cloudapp.azure.com