apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: playeconomyaxsg-tls-cert
spec:
  secretName: playeconomyaxsg-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "playeconomyaxsg1.eastus.cloudapp.azure.com"