apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme: # automated certificate management environment
    server: https://acme-v02.api.letsencrypt.org/directory
    email: andres_s18@outlook.com
    privateKeySecretRef:
      name: letsencrypt-prod-andres
    solvers:
      - http01:
          ingress:
            class: nginx